import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[colors]

draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"
blinking = "Never"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95
title = "Alacritty"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 0
y = 0

[env]
TERM = "xterm-256color"
