-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")

vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set({ "i", "n" }, "<F1>", "<Esc>")
vim.keymap.set("n", "<C-h>", "<C-W>h")
vim.keymap.set("n", "<C-j>", "<C-W>j")
vim.keymap.set("n", "<C-k>", "<C-W>k")
vim.keymap.set("n", "<C-l>", "<C-W>l")
-- vim.keymap.set("n", "<C-h>", require("smart-splits").move_cursor_left)
-- vim.keymap.set("n", "<C-j>", require("smart-splits").move_cursor_down)
-- vim.keymap.set("n", "<C-k>", require("smart-splits").move_cursor_up)
-- vim.keymap.set("n", "<C-l>", require("smart-splits").move_cursor_right)
vim.keymap.set("n", "<leader>e", require("oil").toggle_float)
vim.keymap.set("n", "<leader>snc", function()
  local word = vim.fn.expand("<cword>")
  local snake = word:gsub("([a-z])([A-Z])", "%1_%2"):lower()
  vim.cmd("normal! ciw" .. snake .. "")
end, { desc = "Change inner word to snake_case" })

vim.keymap.set("n", "<leader>mi", ":MoltenInit<CR>")
vim.keymap.set("n", "<leader>me", ":MoltenEvaluateOperator<CR>")
vim.keymap.set("n", "<leader>mm", ":MoltenReevaluateCell<CR>")
vim.keymap.set("v", "<leader>mm", ":<C-u>MoltenEvaluateVisual<CR>gv")
vim.keymap.set("n", "<leader>md", ":noautocmd MoltenEnterOutput<CR>")
vim.keymap.set("n", "<leader>mh", ":MoltenHideOutput<CR>")
vim.keymap.set("n", "<leader>md", ":MoltenDelete<CR>")
